name: "Install ROCm libraries"
description: "Install ROCm libraries on Linux"
inputs:
   rocm_version:
     required: true
     description: "The rocm major and minor version."

runs:
  using: composite
  steps:
    - name: ROCM URL
      id: rocm_url
      run: |
        echo "rocm_url=$(echo $ROCM_URL)" >> $GITHUB_OUTPUT
      shell: bash
        
    - name: Install cuDNN (Linux)
      if: ${{ runner.os == 'Linux' }}
      run: |
          DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends curl libnuma-dev gnupg build-essential
          curl -sL http://repo.radeon.com/rocm/apt/debian/rocm.gpg.key | apt-key add - 
          printf "deb [arch=amd64] http://repo.radeon.com/rocm/apt/debian/ xenial main" | tee /etc/apt/sources.list.d/rocm.list
          apt-get update
          DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends sudo libelf1 rocm-dev rocm-libs rocrand-dev hipfft-dev rocfft-dev hipsparse-dev rocthrust-dev miopen-hip-dev hipcub-dev rccl-dev hipfort-dev

          apt-get clean
          rm -rf /var/lib/apt/lists/*
      shell: bash

